name=FirebaseAutoSensors
version=0.1.0
author=Nino Felino
maintainer=Nino Felino <>
sentence=Automatic sensor registration and send to Firebase Realtime Database
paragraph=Lightweight Arduino library that auto-registers sensor readers and periodically pushes values to Firebase RTDB via REST API. Designed for ESP8266/ESP32.
category=Communication
url=https://example.com
architectures=esp8266,esp32
